name: Continue Elite Configs
version: 4.50.0
schema: v1
models:
  - name: 1.1 Fast | groq/compound-mini | groq | 131k/8k
    provider: groq
    model: groq/compound-mini
    apiKey: ${{ secrets.GROQ_API_KEY }}
  - name: 1.2 Fast | DeepSeek-V3.2 | sambanova | 32k/7k
    provider: sambanova
    model: DeepSeek-V3.2
    apiKey: ${{ secrets.SAMBANOVA_API_KEY }}
  - name: 1.3 Fast | groq/compound | groq | 131k/8k
    provider: groq
    model: groq/compound
    apiKey: ${{ secrets.GROQ_API_KEY }}
  - name: 1.4 Fast | DeepSeek-V3.1 | sambanova | 131k/7k
    provider: sambanova
    model: DeepSeek-V3.1
    apiKey: ${{ secrets.SAMBANOVA_API_KEY }}
  - name: 1.5 Fast | liquid/lfm-2.5-2.6b:free | openrouter | 128k/8k
    provider: openrouter
    model: liquid/lfm-2.5-2.6b:free
    apiKey: ${{ secrets.OPENROUTER_API_KEY }}

  - name: 2.1 Review | qwen/qwen3.6-27b | groq | 131k/16k
    provider: groq
    model: qwen/qwen3.6-27b
    apiKey: ${{ secrets.GROQ_API_KEY }}
  - name: 2.2 Review | openai/gpt-oss-20b | groq | 