name: Continue Elite Configs
version: 4.6.0
schema: v1
models:
  - name: 1.1 Fast | DeepSeek-V3.1-cb | sambanova | 32k/32k
    provider: sambanova
    model: DeepSeek-V3.1-cb
    apiKey: ${{ secrets.SAMBANOVA_API_KEY }}
  - name: 1.2 Fast | DeepSeek-V3.2 | sambanova | 32k/7k
    provider: sambanova
    model: DeepSeek-V3.2
    apiKey: ${{ secrets.SAMBANOVA_API_KEY }}
  - name: 1.3 Fast | groq/compound-mini | groq | 131k/8k
    provider: groq
    model: groq/compound-mini
    apiKey: ${{ secrets.GROQ_API_KEY }}
  - name: 1.4 Fast | llama-3.1-8b-instant | groq | 131k/131k
    provider: groq
    model: llama-3.1-8b-instant
    apiKey: ${{ secrets.GROQ_API_KEY }}
  - name: 1.5 Fast | MiniMax-M2.5 | sambanova | 163k/32k
    provider: sambanova
    model: MiniMax-M2.5
    apiKey: ${{ secrets.SAMBANOVA_API_KEY }}

  - name: 2.1 Refactor Specialist | llama-3.3-70b-versatile | groq | 131k/32k
    provider: groq
    model: llama-3.3-70b-versatile
    apiKey: ${{ secrets.GROQ_API_KEY }}
  - name: 2.2 Refactor Specialist | qwen/qwen3-32b | groq | 131k/40k
    provider: groq
    model: qwen/qwen3-32b
    apiKey: ${{ secrets.GROQ_API_KEY }}
  - name: 2.3 Refactor Specialist | MiniMax-M2.7 | sambanova | 196k/196k
    provider: sambanova
    model: MiniMax-M2.7
    apiKey: ${{ secrets.SAMBANOVA_API_KEY }}
  - name: 2.4 Refactor Specialist | gemini-2.5-pro | gemini | 1048k/65k
    provider: gemini
    model: gemini-2.5-pro
    apiKey: ${{ secrets.GEMINI_API_KEY }}
  - name: 2.5 Refactor Specialist | openai/gpt-oss-120b | openrouter | 131k/131k
    provider: openrouter
    model: openai/gpt-oss-120b:free
    apiKey: ${{ secrets.OPENROUTER_API_KEY }}

  - name: 3.1 Thinker | gemini-2.5-pro | gemini | 1048k/65k
    provider: gemini
    model: gemini-2.5-pro
    apiKey: ${{ secrets.GEMINI_API_KEY }}
  - name: 3.2 Thinker | gemini-pro-latest | gemini | 1048k/65k
    provider: gemini
    model: gemini-pro-latest
    apiKey: ${{ secrets.GEMINI_API_KEY }}
  - name: 3.3 Thinker | gemini-flash-latest | gemini | 1048k/65k
    provider: gemini
    model: gemini-flash-latest
    apiKey: ${{ secrets.GEMINI_API_KEY }}
  - name: 3.4 Thinker | qwen/qwen3-coder | openrouter | 262k/262k
    provider: openrouter
    model: qwen/qwen3-coder:free
    apiKey: ${{ secrets.OPENROUTER_API_KEY }}
  - name: 3.5 Thinker | nvidia/nemotron-3-super-120b-a12b | openrouter | 262k/262k
    provider: openrouter
    model: nvidia/nemotron-3-super-120b-a12b:free
    apiKey: ${{ secrets.OPENROUTER_API_KEY }}